### ISSUE TITLE
Increase font size for smaller screens

### ISSUE THREAD

**Issue by claytoncook** [jadeallencook/Alan-Watts#19]

**Comment by jadeallencook** [comment]
The font sizes are really small on mobile and are inconsistent. 
<img width="372" alt="Screen Shot 2020-01-21 at 2 09 11 PM" src="https://user-images.githubusercontent.com/4443883/72847649-dfa25300-3c57-11ea-8d61-efa0a6b367d9.png">

**Comment by jadeallencook** [comment]
Headers look good at 1.75em and the paragraphs should be 1em. 
<img width="395" alt="Screen Shot 2020-01-21 at 2 14 44 PM" src="https://user-images.githubusercontent.com/4443883/72847955-66efc680-3c58-11ea-8944-7356b9ddd42a.png">
