### ISSUE TITLE
Size and position Youtube thumbnails for smaller screens

### ISSUE THREAD

**Issue by claytoncook** [jadeallencook/Alan-Watts#20]

**Comment by jadeallencook** [comment]
The player good, I'd just change the display of the last video to "none" on mobile. 

<img width="374" alt="Screen Shot 2020-01-21 at 2 18 01 PM" src="https://user-images.githubusercontent.com/4443883/72848164-dbc30080-3c58-11ea-991e-e25732ac9e72.png">
